# Your Solution
services:

  book-catalog:
    image: book-catalog:$VERSION
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
     - "8000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://varunvk_db_w1bo_user:qS6DfvrqZkx4b1foV7ipy5rhUiRDabHa@dpg-cs3q39jtq21c738il970-a.oregon-postgres.render.com/varunvk_db_w1bo
    restart: "no"

  inventory_management:
    image: inventory-management:$VERSION
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
     - "8001:8001"
    environment:
      - PORT=8001
      - DATABASE_URL=postgresql://varunvk_db_w1bo_user:qS6DfvrqZkx4b1foV7ipy5rhUiRDabHa@dpg-cs3q39jtq21c738il970-a.oregon-postgres.render.com/varunvk_db_w1bo
    restart: "no"
