# Your Solution
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vk4041
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vk4041
  template:
    metadata:
      labels:
        app: vk4041
    spec:
      containers:
      - name: book-catalog
        image: $CONTAINER_REGISTRY/book-catalog:$VERSION
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: DATABASE_URL
          value: postgresql://varunvk_db_w1bo_user:qS6DfvrqZkx4b1foV7ipy5rhUiRDabHa@dpg-cs3q39jtq21c738il970-a.oregon-postgres.render.com/varunvk_db_w1bo
      - name: inventory-management
        image: $CONTAINER_REGISTRY/inventory-management:$VERSION
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
        env:
        - name: PORT
          value: "8001"
        - name: DATABASE_URL
          value: postgresql://varunvk_db_w1bo_user:qS6DfvrqZkx4b1foV7ipy5rhUiRDabHa@dpg-cs3q39jtq21c738il970-a.oregon-postgres.render.com/varunvk_db_w1bo

---
apiVersion: v1
kind: Service
metadata:
  name: vk4041
spec:
  selector:
    app: vk4041
  ports:
    - name: book-catalog
      port: 8000
      targetPort: 8000
    - name: inventory-management
      port: 8001
      targetPort: 8001
  type: LoadBalancer
