# Your Solution
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vk4041
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vk4041
  template:
    metadata:
      labels:
        app: vk4041
    spec:
      containers:
      - name: book-catalog
        image: $CONTAINER_REGISTRY/book-catalog:1
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: DATABASE_URL
          value: postgresql://varunvk_db_user:RBCwx49kCyCQ8mFinoHdWoQxJQBC7j0D@dpg-crui6llumphs73ens3ig-a.oregon-postgres.render.com/varunvk_db
      - name: inventory-management
        image: $CONTAINER_REGISTRY/inventory-management:1
        ports:
        - containerPort: 8001
        env:
        - name: PORT
          value: "8001"
        - name: DATABASE_URL
          value: postgresql://varunvk_db_user:RBCwx49kCyCQ8mFinoHdWoQxJQBC7j0D@dpg-crui6llumphs73ens3ig-a.oregon-postgres.render.com/varunvk_db

---
apiVersion: v1
kind: Service
metadata:
  name: vk4041
spec:
  selector:
    app: vk4041
  ports:
    - name: book-catalog
      port: 8000
      targetPort: 8000
    - name: inventory-management
      port: 8001
      targetPort: 8001
  type: LoadBalancer
